# Generated by Django 5.2.6 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_type',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
