# Generated by Django 5.2.6 on 2025-11-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0002_profile_ban_expires_at_profile_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationtype',
            name='icon',
            field=models.CharField(default='📜', help_text='Emoji icon for the certification', max_length=10),
        ),
    ]
