# Generated by Django 5.2.6 on 2025-11-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0003_certificationtype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='icon',
            field=models.CharField(default='fa-solid fa-certificate', help_text='Font Awesome icon class (e.g., fa-solid fa-print)', max_length=100),
        ),
    ]
