# Generated by Django 5.2.7 on 2025-11-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0002_workblock'),
        ('pct', '0004_roomreservation_timeblock'),
    ]

    operations = [
    ]
