# Generated by Django 5.2.6 on 2025-11-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0004_alter_certificationtype_icon'),
        ('pct', '0005_merge_0002_workblock_0004_roomreservation_timeblock'),
    ]

    operations = [
    ]
