# Generated by Django 5.2.6 on 2025-12-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0006_merge_20251120_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TrainingWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='waiting', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='pct.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='pct.training')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('training', 'profile')},
            },
        ),
    ]
