# Generated by Django 5.2.6 on 2025-11-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0006_merge_20251120_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('team_member', 'Team Member')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['student', 'staff', 'team_member']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_booked', to='pct.profile'),
        ),
    ]
