# Generated by ChatGPT on 2025-12-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pct', '0007_alter_profile_role_alter_training_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('team_member', 'Team Member')], default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Use the Monday of the week.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks_created', to='pct.profile')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start',)},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('min_staffing', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='pct.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to='pct.profile')),
                ('schedule_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pct.scheduleweek')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_give_up', models.BooleanField(default=False, help_text='Set when requester is giving up the shift without a proposed partner.')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to='pct.profile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='pct.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_reviewed', to='pct.profile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='pct.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='pct.profile')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='pct.scheduleweek')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AlterField(
            model_name='training',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['student', 'team_member', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_booked', to='pct.profile'),
        ),
    ]
