# Generated by ChatGPT on 2025-12-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0008_team_member_and_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OpenHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='pct.semester')),
            ],
            options={
                'ordering': ['weekday', 'open_time'],
                'unique_together': {('semester', 'weekday', 'open_time', 'close_time')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='pct.semester')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('semester', 'date')},
            },
        ),
    ]
