# Generated by Django 5.2.7 on 2025-12-04 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0010_shift_availability_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='is_exclusive_request',
            field=models.BooleanField(default=False, help_text='Mark when the requester needs exclusive classroom/station access for a course/event.'),
        ),
        migrations.CreateModel(
            name='TrainingCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_cancellations', to='pct.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_cancellations_reviewed', to='pct.profile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='pct.training')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('training', 'requester', 'status')},
            },
        ),
    ]
