# Generated by Django 5.2.6 on 2025-12-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0007_activitylog_report'),
        ('pct', '0010_shift_availability_skills'),
    ]

    operations = [
    ]
