# Generated by Django 5.2.7 on 2025-12-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0007_training_capacity_trainingwaitlist'),
        ('pct', '0011_merge_20251202_1613'),
    ]

    operations = [
    ]
