# Generated by Django 5.2.7 on 2025-12-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pct', '0011_roomreservation_is_exclusive_request_and_more'),
        ('pct', '0012_merge_20251203_1204'),
    ]

    operations = [
    ]
